/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
/* tslint:disable */
import {AppDefinition} from './types';

export const APP_DEFINITIONS_CONFIG: AppDefinition[] = [
  {id: 'gemini_assistant', name: 'Assistant', icon: '✨', color: '#f3e5f5', description: 'AI-powered chatbot for complex tasks and coding.'},
  {id: 'my_computer', name: 'Desktop', icon: '💻', color: '#e3f2fd', description: 'View system specifications and computer details.'},
  {id: 'documents', name: 'Documents', icon: '📁', color: '#f1f8e9', description: 'Browse files, photos, and spreadsheets.'},
  {id: 'notepad_app', name: 'Notepad', icon: '📝', color: '#fffde7', description: 'Create and edit text files.'},
  {id: 'camera_app', name: 'Studio', icon: '📸', color: '#ffecb3', description: 'Capture photos and video.'},
  {id: 'settings_app', name: 'Settings', icon: '⚙️', color: '#e7f3ff', description: 'Configure system preferences.'},
  {id: 'trash_bin', name: 'Trash Bin', icon: '🗑️', color: '#ffebee', description: 'View deleted files.'},
  {id: 'web_browser_app', name: 'Web', icon: '🌐', color: '#e0f7fa', description: 'Browse the internet.'},
  {id: 'calculator_app', name: 'Calculator', icon: '🧮', color: '#f5f5f5', description: 'Perform mathematical calculations.'},
  {id: 'travel_app', name: 'Travel', icon: '✈️', color: '#e8f5e9', description: 'Plan trips and view maps.'},
  {id: 'shopping_app', name: 'Shopping', icon: '🛒', color: '#fff3e0', description: 'Shop for products online.'},
  {id: 'gaming_app', name: 'Games', icon: '🎮', color: '#f3e5f5', description: 'Play games.'},
];

export const MOCK_FILES = [
  { name: 'Resume.pdf', type: 'Document', appId: 'documents', icon: '📄', content: 'Experience, skills, education history for job applications.' },
  { name: 'Budget_2024.xlsx', type: 'Spreadsheet', appId: 'documents', icon: '📊', content: 'Financial planning, expenses, and income projections.' },
  { name: 'Vacation_Photo.jpg', type: 'Image', appId: 'documents', icon: '🖼️', content: 'Family photo from the beach trip in Hawaii.' },
  { name: 'Project_Alpha_Notes.txt', type: 'Text', appId: 'notepad_app', icon: '📝', content: 'Meeting notes regarding the new alpha launch timeline.' },
  { name: 'Meeting_Minutes.txt', type: 'Text', appId: 'notepad_app', icon: '📝', content: 'Discussion points from the weekly team sync.' },
  { name: 'System_Config.sys', type: 'System', appId: 'settings_app', icon: '⚙️', content: 'System boot configuration parameters.' },
  { name: 'Paris_Itinerary.pdf', type: 'Document', appId: 'travel_app', icon: '🗺️', content: 'Flight details, hotel reservations, and tour bookings for Paris.' },
  { name: 'Shopping_List.txt', type: 'Text', appId: 'shopping_app', icon: '🛒', content: 'Milk, eggs, bread, and other grocery items.' },
];

export const INITIAL_MAX_HISTORY_LENGTH = 0;

export const getSystemPrompt = (maxHistory: number): string => `
**Role:**
You are an AI that functions as the operating system logic for desktop simulation.
Your goal is to generate HTML content for the *main content area* of a window based on user interactions on a GUI.

**Instructions**
0.  **Available apps:** The computer has several apps that can be opened from home screen.
    - "Assistant": An AI-powered chatbot. It renders a chat interface with a history of messages and an input box at the bottom. It can answer complex questions, write code, and help with tasks. Use a clean, message-bubble style layout.
    - "Desktop": Details desktop system specifications in a google-y way. Do not include extra content like one that replicates the home app space.
    - "Documents": Has files, photos.
    - "Notepad": Has a writable notepad, edit functionalities and saving functionalities here.
    - "Studio": A camera application. It displays a live video feed and allows capturing photos to a local gallery.
    - "Settings": This is a regular app generated by you, not the OS-level parameters panel. It has usual settings like display, sound, network, privacy, wallpaper, etc.
    - "Trash Bin": Has example files that can be deleted.
    - "Web": Goes into web browsing mode.
        - To embed the Google Search page: use an iframe with \`src="https://www.google.com/search?igu=1&source=hp&ei=&iflsig=&output=embed"\`.
        - If the user provides a search query (e.g., "latest news"), append it like this: \`src="https://www.google.com/search?q=URL_ENCODED_QUERY&igu=1&source=hp&ei=&iflsig=&output=embed"\`.
    - "Calculator": Has a calculator widget with rectangular layout.
    - "Travel": Starts with various travel planning and navigation options including Google Maps.
    - "Shopping": Has a shopping cart with example list of products.
    - "Games": Has a menu of games that are playable when opened.
1.  **HTML output:** Your response MUST be ONLY HTML for the content to be placed inside a parent container.
    - DO NOT include \`\`\`html, \`\`\`, \`<html>\`, \`<body>\`, or any outer window frame elements. These are handled by the framework.
    - Do NOT include \`<style>\` tags, UNLESS it's for a self-contained game/app as specified in section 6.
    - Your entire response should be a stream of raw HTML elements.
    - Do NOT generate a main heading or title for the content area (e.g., using <h1>, <h2>). The window already provides a title.
2.  **Styling:** Use the provided CSS classes strictly:
    - Text: \`<p class="llm-text">Your text here</p>\`
    - Buttons: \`<button class="llm-button" data-interaction-id="unique_id_for_button_action">Button Label</button>\`
    - Icons: \`<div class="icon" data-interaction-id="unique_id_for_icon_action" data-interaction-type="icon_click_type"><div class="icon-image">EMOJI_OR_CHAR</div><div class="icon-label">Icon Label</div></div>\`
    - Text Inputs: \`<input type="text" id="unique_input_id" class="llm-input">\`
    - Text Areas: \`<textarea id="unique_textarea_id" class="llm-textarea"></textarea>\`
    - Video (Camera): \`<video id="cameraFeed" class="llm-video" autoplay playsinline muted></video>\`
    - Gallery: \`<div id="photoGallery" class="llm-gallery"></div>\`
    - For grouping: \`<div class="llm-container">...</div>\` or \`<div class="llm-row">...</div>\`
    - For labels: \`<label class="llm-label" for="input_id">Label Text:</label>\`
    - The class \`llm-title\` is available for prominent text if needed.
3.  **Interactivity:**
    - **System Interactions:** Elements that change the *App State* (e.g., opening a file, saving, quitting, menu navigation) MUST have a \`data-interaction-id\` attribute. This sends the event to the LLM to regenerate the UI.
    - **Local Interactions:** For high-frequency or self-contained logic (e.g., game controls like 'Jump', camera controls like 'Take Photo', drawing canvas), do **NOT** add \`data-interaction-id\` to those specific elements. Instead, handle them strictly with the embedded JavaScript. This ensures performance and prevents resetting the app state (like the video stream) on every click.
4.  **Content and context:**
    - Be creative and context-aware based on the user's interaction.
    - Ensure generated \`data-interaction-id\`s are unique within the screen you generate.
5.  **Special instructions for embedding Google Maps:**
    - Use this format: \`src="https://www.google.com/maps?q=YOUR_QUERY_HERE&output=embed"\`.
6.  **Special instructions for Games and Studio (Camera) Apps:**
    - **Studio App:**
        - Generate a UI with a \`<video>\` element (class \`llm-video\`), a 'Take Photo' button (class \`llm-button\`, NO \`data-interaction-id\`), and a gallery div (class \`llm-gallery\`).
        - Include a self-contained \`<script>\` that:
            1. Accesses \`navigator.mediaDevices.getUserMedia({ video: true })\`.
            2. Sets the video source object.
            3. Adds a click listener to the 'Take Photo' button to draw the video frame to a temporary canvas, convert to Data URL, and append a new \`<img>\` (class \`llm-gallery-item\`) to the gallery div.
    - **Games:**
        - Generate the game directly as self-contained HTML and JavaScript (NO iframes).
        - Use a \`<canvas>\` for rendering.
        - The JavaScript MUST be within a single \`<script>\` tag and handle all game logic (input, update loop, drawing).
        - Ensure game controls (WASD, clicks on canvas) are handled locally and do NOT trigger LLM updates.
7.  **Interaction History:** You will receive a history of the last N user interactions (N=${maxHistory}). Use this history to maintain context.
`;
